#!/usr/bin/env bash
# Stage 3 v2-wire e2e — runs against `wrangler dev --port <p>` with the v2
# KV flag ENABLED in dev (ops:x402v2_enabled=true in local PRICING KV).
# Failing-test-first: this script was written BEFORE the /v2 route existed;
# every assertion below must pass once Stage 3 lands.
#
# Prereqs: local KV seeded (pricing + ops:x402v2_enabled), .dev.vars with
# V2_STAMP_KEY, local D1 migrated.
set -u
PORT="${1:-8799}"
BASE="http://127.0.0.1:$PORT"
PASS=0; FAIL=0
check() { # name expected actual
  if [ "$2" = "$3" ]; then PASS=$((PASS+1)); echo "ok   $1"; else FAIL=$((FAIL+1)); echo "FAIL $1: expected [$2] got [$3]"; fi
}

TOOL=vat-mod97-check
ROUTE="$BASE/v2/tools/$TOOL/call"
BODY='{"input":{"vat_number":"GB123456789"}}'

# 1. POST without payment -> 402 with PAYMENT-REQUIRED header
HDRS=$(curl -s -D - -o /tmp/v2-402-body.json --max-time 10 -X POST "$ROUTE" -H 'content-type: application/json' -d "$BODY")
PR=$(echo "$HDRS" | tr -d '\r' | grep -i '^payment-required: ' | cut -d' ' -f2-)
check "402 status" "402" "$(echo "$HDRS" | head -1 | grep -o '[0-9][0-9][0-9]')"
check "PAYMENT-REQUIRED present" "yes" "$([ -n "$PR" ] && echo yes || echo no)"

# 2. header decodes to a spec-valid issuance (via our codec, python check below)
python - "$PR" << 'PYEOF' && check "header is issuance-valid" "yes" "yes" || check "header is issuance-valid" "yes" "no"
import base64, json, sys
raw = base64.b64decode(sys.argv[1])
d = json.loads(raw)
assert d["x402Version"] == 2
assert d["resource"]["url"].endswith("/v2/tools/vat-mod97-check/call")
a = d["accepts"][0]
assert a["scheme"] == "exact" and a["network"].startswith("eip155:")
assert a["extra"]["paymentFlow"] == "upfront"
assert a["extra"]["assetTransferMethod"] == "eip3009"
assert a["extra"]["name"] and a["extra"]["version"]
ext = d.get("extensions", {})
stamp = ext.get("code402.stamp", {})
assert "mac" in stamp.get("info", {}) and "iat" in stamp.get("info", {})
PYEOF

# 3. CORS: expose payment headers on 402; allow PAYMENT-SIGNATURE on preflight
N=$(echo "$HDRS" | tr -d '
' | grep -ci 'access-control-expose-headers: .*payment-required'); check "expose-headers on 402" "yes" "$([ "$N" -ge 1 ] && echo yes || echo no)"
PRE=$(curl -s -D - -o /dev/null --max-time 10 -X OPTIONS "$ROUTE" -H 'Origin: https://example.com' -H 'Access-Control-Request-Method: POST' -H 'Access-Control-Request-Headers: PAYMENT-SIGNATURE')
N2=$(echo "$PRE" | tr -d '
' | grep -ci 'access-control-allow-headers: .*payment-signature'); check "preflight allows PAYMENT-SIGNATURE" "yes" "$([ "$N2" -ge 1 ] && echo yes || echo no)"

# 4. duplicate payment headers -> 400
check "duplicate header rejected" "400" "$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 -X POST "$ROUTE" -H 'content-type: application/json' -H 'PAYMENT-SIGNATURE: AAAA' -H 'PAYMENT-SIGNATURE: BBBB' -d "$BODY")"

# 5. garbage payment header -> 4xx taxonomy error, NOT 5xx
G=$(curl -s -o /tmp/v2-g.json -w '%{http_code}' --max-time 10 -X POST "$ROUTE" -H 'content-type: application/json' -H 'PAYMENT-SIGNATURE: !!!notbase64!!!' -d "$BODY")
check "garbage sig 4xx" "yes" "$([ "$G" -ge 400 ] && [ "$G" -lt 500 ] && echo yes || echo no)"

# 6. valid signed payment (generated by cargo keygen payv2) -> passes gates -> 200
if [ -n "${V2_PAY_FILE:-}" ] && [ -f "$V2_PAY_FILE" ]; then
  SIG=$(cat "$V2_PAY_FILE")
  R=$(curl -s -D /tmp/v2-200-h.txt -o /tmp/v2-200.json --max-time 15 -X POST "$ROUTE" -H 'content-type: application/json' -H "PAYMENT-SIGNATURE: $SIG" -d "$BODY" -w '%{http_code}')
  check "valid payment 200" "200" "$R"
  check "output present" "yes" "$(grep -q '"output"' /tmp/v2-200.json && echo yes || echo no)"
  check "receipt present" "yes" "$(grep -q '"receipt"' /tmp/v2-200.json && echo yes || echo no)"
else
  echo "skip valid-payment test (V2_PAY_FILE unset — generate with keygen payv2)"
fi

echo "----"
echo "pass=$PASS fail=$FAIL"
[ "$FAIL" -eq 0 ]
