[package]
name = "m2m-core"
version.workspace = true
edition.workspace = true

[dependencies]
alloy-primitives.workspace = true
alloy-sol-types.workspace = true
base64 = "0.22"
k256.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
hex = "0.4"
sha2 = "0.10"
